version: '2'
services:
    gisthub-app:
        image: gisthub
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://gisthub-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=Gisthub
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gisthub-mongodb:
        extends:
            file: mongodb.yml
            service: gisthub-mongodb
